// Generated by ReScript, PLEASE EDIT WITH CARE


var formatter = new Intl.DateTimeFormat(undefined, {
      dateStyle: "full",
      timeStyle: "full"
    });

console.log(formatter.format(new Date(Date.now())));

console.log(formatter.formatRange(new Date(2023, 1, 1), new Date(2023, 12, 31)));

var formatter$1 = new Intl.DateTimeFormat(undefined, {
      timeZone: "UTC",
      hour12: false,
      hourCycle: "h24",
      weekday: "narrow",
      era: "narrow",
      year: "2-digit",
      month: "2-digit",
      day: "2-digit",
      hour: "2-digit",
      minute: "2-digit",
      second: "2-digit",
      fractionalSecondDigits: 3,
      timeZoneName: "short"
    });

console.log(formatter$1.format(new Date(Date.now())));

var resolvedOptions = new Intl.DateTimeFormat().resolvedOptions();

var timeZone = resolvedOptions.timeZone;

export {
  formatter$1 as formatter,
  resolvedOptions ,
  timeZone ,
}
/* formatter Not a pure module */
