// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Test from "./Test.mjs";
import * as Curry from "rescript/lib/es6/curry.js";
import * as Js_exn from "rescript/lib/es6/js_exn.js";
import * as Caml_obj from "rescript/lib/es6/caml_obj.js";
import * as Core__Int from "../src/Core__Int.mjs";
import * as Pervasives from "rescript/lib/es6/pervasives.js";
import * as Caml_js_exceptions from "rescript/lib/es6/caml_js_exceptions.js";

var eq = Caml_obj.equal;

function $$catch(f) {
  try {
    Curry._1(f, undefined);
    return Pervasives.failwith("no exception raised");
  }
  catch (raw_err){
    var err = Caml_js_exceptions.internalToOCamlException(raw_err);
    if (err.RE_EXN_ID === Js_exn.$$Error) {
      return err._1;
    }
    throw err;
  }
}

Test.run([
      [
        "IntTests.res",
        13,
        20,
        32
      ],
      "fromString"
    ], Core__Int.fromString("4.2"), eq, undefined);

Test.run([
      [
        "IntTests.res",
        14,
        20,
        32
      ],
      "fromString"
    ], Core__Int.fromString("4."), eq, 4);

Test.run([
      [
        "IntTests.res",
        15,
        20,
        32
      ],
      "fromString"
    ], Core__Int.fromString("4.0"), eq, 4);

Test.run([
      [
        "IntTests.res",
        16,
        20,
        32
      ],
      "fromString"
    ], Core__Int.fromString("4.2foo"), eq, undefined);

Test.run([
      [
        "IntTests.res",
        17,
        20,
        32
      ],
      "fromString"
    ], Core__Int.fromString("4,2"), eq, undefined);

Test.run([
      [
        "IntTests.res",
        18,
        20,
        32
      ],
      "fromString"
    ], Core__Int.fromString("4 2"), eq, undefined);

Test.run([
      [
        "IntTests.res",
        19,
        20,
        32
      ],
      "fromString"
    ], Core__Int.fromString("4_2"), eq, undefined);

Test.run([
      [
        "IntTests.res",
        20,
        20,
        32
      ],
      "fromString"
    ], Core__Int.fromString("42"), eq, 42);

Test.run([
      [
        "IntTests.res",
        21,
        20,
        32
      ],
      "fromString"
    ], Core__Int.fromString("  42  "), eq, 42);

Test.run([
      [
        "IntTests.res",
        22,
        20,
        32
      ],
      "fromString"
    ], Core__Int.fromString("4.2e1"), eq, 42);

Test.run([
      [
        "IntTests.res",
        23,
        20,
        32
      ],
      "fromString"
    ], Core__Int.fromString("4.2E1"), eq, 42);

Test.run([
      [
        "IntTests.res",
        24,
        20,
        32
      ],
      "fromString"
    ], Core__Int.fromString("4.2e+1"), eq, 42);

Test.run([
      [
        "IntTests.res",
        25,
        20,
        32
      ],
      "fromString"
    ], Core__Int.fromString("4.2e-1"), eq, undefined);

Test.run([
      [
        "IntTests.res",
        26,
        20,
        32
      ],
      "fromString"
    ], Core__Int.fromString("0xF"), eq, 15);

Test.run([
      [
        "IntTests.res",
        27,
        20,
        32
      ],
      "fromString"
    ], Core__Int.fromString("0777"), eq, 777);

Test.run([
      [
        "IntTests.res",
        28,
        20,
        32
      ],
      "fromString"
    ], Core__Int.fromString("0o777"), eq, 511);

Test.run([
      [
        "IntTests.res",
        29,
        20,
        32
      ],
      "fromString"
    ], Core__Int.fromString("0b101"), eq, 5);

Test.run([
      [
        "IntTests.res",
        30,
        20,
        32
      ],
      "fromString"
    ], Core__Int.fromString("foo"), eq, undefined);

Test.run([
      [
        "IntTests.res",
        31,
        20,
        32
      ],
      "fromString"
    ], Core__Int.fromString("NaN"), eq, undefined);

Test.run([
      [
        "IntTests.res",
        32,
        20,
        32
      ],
      "fromString"
    ], Core__Int.fromString("Infinity"), eq, undefined);

Test.run([
      [
        "IntTests.res",
        34,
        20,
        50
      ],
      "range - positive, increasing"
    ], Core__Int.range(3, 6), eq, [
      3,
      4,
      5
    ]);

Test.run([
      [
        "IntTests.res",
        35,
        20,
        50
      ],
      "range - negative, increasing"
    ], Core__Int.range(-3, -1), eq, [
      -3,
      -2
    ]);

Test.run([
      [
        "IntTests.res",
        36,
        20,
        51
      ],
      "range - cross-zero, incresing"
    ], Core__Int.range(-1, 2), eq, [
      -1,
      0,
      1
    ]);

Test.run([
      [
        "IntTests.res",
        37,
        20,
        42
      ],
      "range - start == end"
    ], Core__Int.range(3, 3), eq, []);

Test.run([
      [
        "IntTests.res",
        38,
        20,
        50
      ],
      "range - positive, decreasing"
    ], Core__Int.range(3, 1), eq, [
      3,
      2
    ]);

Test.run([
      [
        "IntTests.res",
        39,
        20,
        50
      ],
      "range - negative, decreasing"
    ], Core__Int.range(-1, -3), eq, [
      -1,
      -2
    ]);

Test.run([
      [
        "IntTests.res",
        42,
        13,
        62
      ],
      "rangeWithOptions - positive, increasing, step 2"
    ], Core__Int.rangeWithOptions(3, 6, {
          step: 2
        }), eq, [
      3,
      5
    ]);

Test.run([
      [
        "IntTests.res",
        48,
        13,
        62
      ],
      "rangeWithOptions + positive, increasing, step 2"
    ], Core__Int.rangeWithOptions(3, 7, {
          step: 2
        }), eq, [
      3,
      5
    ]);

Test.run([
      [
        "IntTests.res",
        54,
        13,
        62
      ],
      "rangeWithOptions + positive, increasing, step 2"
    ], Core__Int.rangeWithOptions(3, 8, {
          step: 2
        }), eq, [
      3,
      5,
      7
    ]);

Test.run([
      [
        "IntTests.res",
        60,
        13,
        62
      ],
      "rangeWithOptions - negative, increasing, step 2"
    ], Core__Int.rangeWithOptions(-6, -3, {
          step: 2
        }), eq, [
      -6,
      -4
    ]);

Test.run([
      [
        "IntTests.res",
        66,
        13,
        62
      ],
      "rangeWithOptions - positive, increasing, step 0"
    ], $$catch(function (param) {
          return Core__Int.rangeWithOptions(3, 6, {
                      step: 0
                    });
        }), eq, new RangeError("Incorrect range arguments"));

Test.run([
      [
        "IntTests.res",
        72,
        13,
        54
      ],
      "rangeWithOptions - start == end, step 0"
    ], Core__Int.rangeWithOptions(3, 3, {
          step: 0
        }), eq, []);

Test.run([
      [
        "IntTests.res",
        78,
        13,
        63
      ],
      "rangeWithOptions + positive, increasing, step -1"
    ], Core__Int.rangeWithOptions(3, 6, {
          step: -1
        }), eq, []);

Test.run([
      [
        "IntTests.res",
        84,
        13,
        62
      ],
      "rangeWithOptions + positive, decreasing, step 1"
    ], Core__Int.rangeWithOptions(6, 3, {
          step: 1
        }), eq, []);

Test.run([
      [
        "IntTests.res",
        90,
        13,
        63
      ],
      "rangeWithOptions + positive, decreasing, step -2"
    ], Core__Int.rangeWithOptions(6, 3, {
          step: -2
        }), eq, [
      6,
      4
    ]);

Test.run([
      [
        "IntTests.res",
        96,
        13,
        63
      ],
      "rangeWithOptions + positive, increasing, step -2"
    ], Core__Int.rangeWithOptions(6, 2, {
          step: -2
        }), eq, [
      6,
      4
    ]);

Test.run([
      [
        "IntTests.res",
        102,
        13,
        63
      ],
      "rangeWithOptions + positive, increasing, step -2"
    ], Core__Int.rangeWithOptions(6, 1, {
          step: -2
        }), eq, [
      6,
      4,
      2
    ]);

Test.run([
      [
        "IntTests.res",
        108,
        13,
        63
      ],
      "rangeWithOptions + negative, decreasing, step -2"
    ], Core__Int.rangeWithOptions(-3, -6, {
          step: -2
        }), eq, [
      -3,
      -5
    ]);

Test.run([
      [
        "IntTests.res",
        114,
        13,
        73
      ],
      "rangeWithOptions - positive, increasing, step 2, inclusive"
    ], Core__Int.rangeWithOptions(3, 6, {
          step: 2,
          inclusive: true
        }), eq, [
      3,
      5
    ]);

Test.run([
      [
        "IntTests.res",
        120,
        13,
        73
      ],
      "rangeWithOptions + positive, increasing, step 2, inclusive"
    ], Core__Int.rangeWithOptions(3, 7, {
          step: 2,
          inclusive: true
        }), eq, [
      3,
      5,
      7
    ]);

Test.run([
      [
        "IntTests.res",
        126,
        13,
        73
      ],
      "rangeWithOptions + positive, increasing, step 2, inclusive"
    ], Core__Int.rangeWithOptions(3, 8, {
          step: 2,
          inclusive: true
        }), eq, [
      3,
      5,
      7
    ]);

Test.run([
      [
        "IntTests.res",
        132,
        13,
        73
      ],
      "rangeWithOptions - negative, increasing, step 2, inclusive"
    ], Core__Int.rangeWithOptions(-6, -3, {
          step: 2,
          inclusive: true
        }), eq, [
      -6,
      -4
    ]);

Test.run([
      [
        "IntTests.res",
        138,
        13,
        73
      ],
      "rangeWithOptions - positive, increasing, step 0, inclusive"
    ], $$catch(function (param) {
          return Core__Int.rangeWithOptions(3, 6, {
                      step: 0,
                      inclusive: true
                    });
        }), eq, new RangeError("Incorrect range arguments"));

Test.run([
      [
        "IntTests.res",
        144,
        13,
        65
      ],
      "rangeWithOptions - start == end, step 0, inclusive"
    ], Core__Int.rangeWithOptions(3, 3, {
          step: 0,
          inclusive: true
        }), eq, [3]);

Test.run([
      [
        "IntTests.res",
        150,
        13,
        74
      ],
      "rangeWithOptions + positive, increasing, step -1, inclusive"
    ], Core__Int.rangeWithOptions(3, 6, {
          step: -1,
          inclusive: true
        }), eq, []);

Test.run([
      [
        "IntTests.res",
        156,
        13,
        73
      ],
      "rangeWithOptions + positive, decreasing, step 1, inclusive"
    ], Core__Int.rangeWithOptions(6, 3, {
          step: 1,
          inclusive: true
        }), eq, []);

Test.run([
      [
        "IntTests.res",
        162,
        13,
        74
      ],
      "rangeWithOptions + positive, decreasing, step -2, inclusive"
    ], Core__Int.rangeWithOptions(6, 3, {
          step: -2,
          inclusive: true
        }), eq, [
      6,
      4
    ]);

Test.run([
      [
        "IntTests.res",
        168,
        13,
        74
      ],
      "rangeWithOptions + positive, increasing, step -2, inclusive"
    ], Core__Int.rangeWithOptions(6, 2, {
          step: -2,
          inclusive: true
        }), eq, [
      6,
      4,
      2
    ]);

Test.run([
      [
        "IntTests.res",
        174,
        13,
        74
      ],
      "rangeWithOptions + positive, increasing, step -2, inclusive"
    ], Core__Int.rangeWithOptions(6, 1, {
          step: -2,
          inclusive: true
        }), eq, [
      6,
      4,
      2
    ]);

Test.run([
      [
        "IntTests.res",
        180,
        13,
        74
      ],
      "rangeWithOptions + negative, decreasing, step -2, inclusive"
    ], Core__Int.rangeWithOptions(-3, -6, {
          step: -2,
          inclusive: true
        }), eq, [
      -3,
      -5
    ]);

export {
  eq ,
  $$catch ,
}
/*  Not a pure module */
