// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Test from "./Test.mjs";
import * as Caml_obj from "rescript/lib/es6/caml_obj.js";
import * as Core__Null from "../src/Core__Null.mjs";
import * as Core__Nullable from "../src/Core__Nullable.mjs";

var eq = Caml_obj.equal;

Test.run([
      [
        "NullableTests.res",
        7,
        20,
        38
      ],
      "isNull when null"
    ], Core__Nullable.isNull(null), eq, true);

Test.run([
      [
        "NullableTests.res",
        8,
        20,
        39
      ],
      "isNull when undef"
    ], Core__Nullable.isNull(undefined), eq, false);

Test.run([
      [
        "NullableTests.res",
        9,
        20,
        37
      ],
      "isNull when abc"
    ], Core__Nullable.isNull("abc"), eq, false);

Test.run([
      [
        "NullableTests.res",
        10,
        20,
        38
      ],
      "isNull when None"
    ], Core__Nullable.isNull(undefined), eq, false);

Test.run([
      [
        "NullableTests.res",
        12,
        20,
        39
      ],
      "isUndef when null"
    ], Core__Nullable.isUndefined(null), eq, false);

Test.run([
      [
        "NullableTests.res",
        13,
        20,
        40
      ],
      "isUndef when undef"
    ], Core__Nullable.isUndefined(undefined), eq, true);

Test.run([
      [
        "NullableTests.res",
        14,
        20,
        38
      ],
      "isUndef when abc"
    ], Core__Nullable.isUndefined("abc"), eq, false);

Test.run([
      [
        "NullableTests.res",
        15,
        20,
        39
      ],
      "isUndef when None"
    ], Core__Nullable.isUndefined(undefined), eq, true);

Test.run([
      [
        "NullableTests.res",
        17,
        20,
        45
      ],
      "isNullOrUndef when null"
    ], Core__Nullable.isNullOrUndefined(null), eq, true);

Test.run([
      [
        "NullableTests.res",
        19,
        13,
        39
      ],
      "isNullOrUndef when undef"
    ], Core__Nullable.isNullOrUndefined(undefined), eq, true);

Test.run([
      [
        "NullableTests.res",
        25,
        13,
        37
      ],
      "isNullOrUndef when abc"
    ], Core__Nullable.isNullOrUndefined("abc"), eq, false);

Test.run([
      [
        "NullableTests.res",
        31,
        13,
        38
      ],
      "isNullOrUndef when None"
    ], Core__Nullable.isNullOrUndefined(undefined), eq, true);

Test.run([
      [
        "NullableTests.res",
        37,
        20,
        56
      ],
      "isNull when null using Null module"
    ], Core__Null.isNull(null), eq, true);

Test.run([
      [
        "NullableTests.res",
        39,
        13,
        50
      ],
      "isNull when undef using Null module"
    ], Core__Null.isNull(undefined), eq, false);

Test.run([
      [
        "NullableTests.res",
        44,
        20,
        55
      ],
      "isNull when abc using Null module"
    ], Core__Null.isNull("abc"), eq, false);

Test.run([
      [
        "NullableTests.res",
        45,
        20,
        56
      ],
      "isNull when None using Null module"
    ], Core__Null.isNull(undefined), eq, false);

export {
  eq ,
}
/*  Not a pure module */
