// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Test from "./Test.mjs";
import * as Caml_obj from "rescript/lib/es6/caml_obj.js";
import * as Core__Option from "../src/Core__Option.mjs";

var eq = Caml_obj.equal;

Test.run([
      [
        "OptionTests.res",
        5,
        20,
        25
      ],
      "all"
    ], Core__Option.all([]), eq, []);

Test.run([
      [
        "OptionTests.res",
        6,
        20,
        25
      ],
      "all"
    ], Core__Option.all([
          1,
          2,
          3
        ]), eq, [
      1,
      2,
      3
    ]);

Test.run([
      [
        "OptionTests.res",
        7,
        20,
        25
      ],
      "all"
    ], Core__Option.all([
          1,
          undefined
        ]), eq, undefined);

export {
  eq ,
}
/*  Not a pure module */
