// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Test from "./Test.mjs";
import * as Caml_obj from "rescript/lib/es6/caml_obj.js";
import * as Core__Option from "../src/Core__Option.mjs";

var eq = Caml_obj.equal;

function isPositive(i) {
  return i > 0;
}

Test.run([
      [
        "OptionTests.res",
        12,
        13,
        47
      ],
      "isSomeAnd: if None, return false"
    ], Core__Option.isSomeAnd(undefined, isPositive), eq, false);

Test.run([
      [
        "OptionTests.res",
        19,
        13,
        55
      ],
      "isSomeAnd: if Some and true, return true"
    ], Core__Option.isSomeAnd(1, isPositive), eq, true);

Test.run([
      [
        "OptionTests.res",
        25,
        13,
        57
      ],
      "isSomeAnd: if Some and false, return false"
    ], Core__Option.isSomeAnd(-1, isPositive), eq, false);

Test.run([
      [
        "OptionTests.res",
        31,
        20,
        52
      ],
      "isNoneOr: if None, return true"
    ], Core__Option.isNoneOr(undefined, isPositive), eq, true);

Test.run([
      [
        "OptionTests.res",
        33,
        13,
        54
      ],
      "isNoneOr: if Some and true, return true"
    ], Core__Option.isNoneOr(1, isPositive), eq, true);

Test.run([
      [
        "OptionTests.res",
        39,
        13,
        56
      ],
      "isNoneOr: if Some and false, return false"
    ], Core__Option.isNoneOr(-1, isPositive), eq, false);

export {
  eq ,
  isPositive ,
}
/*  Not a pure module */
