// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Test from "./Test.mjs";
import * as Caml_obj from "rescript/lib/es6/caml_obj.js";
import * as Core__Result from "../src/Core__Result.mjs";

var eq = Caml_obj.equal;

function forEachIfOkCallFunction(param) {
  var called = {
    contents: []
  };
  Core__Result.forEach({
        TAG: /* Ok */0,
        _0: 3
      }, (function (i) {
          called.contents.push(i);
        }));
  Test.run([
        [
          "ResultTests.res",
          12,
          22,
          72
        ],
        "forEach: if ok, call function with ok value once"
      ], called.contents, eq, [3]);
}

forEachIfOkCallFunction(undefined);

function forEachIfErrorDoNotCallFunction(param) {
  var called = {
    contents: []
  };
  Core__Result.forEach({
        TAG: /* Error */1,
        _0: 3
      }, (function (i) {
          called.contents.push(i);
        }));
  Test.run([
        [
          "ResultTests.res",
          19,
          22,
          63
        ],
        "forEach: if error, do not call function"
      ], called.contents, eq, []);
}

forEachIfErrorDoNotCallFunction(undefined);

export {
  eq ,
  forEachIfOkCallFunction ,
  forEachIfErrorDoNotCallFunction ,
}
/*  Not a pure module */
