// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Test from "./Test.mjs";
import * as Caml_obj from "rescript/lib/es6/caml_obj.js";
import * as Core__Result from "../src/Core__Result.mjs";

var eq = Caml_obj.equal;

Test.run([
      [
        "ResultTests.res",
        9,
        20,
        48
      ],
      "mapError: if ok, return it"
    ], Core__Result.mapError({
          TAG: /* Ok */0,
          _0: 5
        }, (function (i) {
            return Math.imul(i, 3);
          })), eq, {
      TAG: /* Ok */0,
      _0: 5
    });

Test.run([
      [
        "ResultTests.res",
        12,
        13,
        42
      ],
      "mapError: if error, apply f"
    ], Core__Result.mapError({
          TAG: /* Error */1,
          _0: 5
        }, (function (i) {
            return Math.imul(i, 3);
          })), eq, {
      TAG: /* Error */1,
      _0: 15
    });

export {
  eq ,
}
/*  Not a pure module */
