// Generated by ReScript, PLEASE EDIT WITH CARE


console.log("---");

console.log("Intl.ListFormat");

new Intl.ListFormat(undefined, undefined);

new Intl.ListFormat([
      "en-US",
      "en-GB"
    ], undefined);

var _formatter = new Intl.ListFormat([
      "en-US",
      "en-GB"
    ], {
      type: "conjunction",
      style: "long"
    });

Intl.ListFormat.supportedLocalesOf([
      "en-US",
      "en-GB"
    ], undefined);

Intl.ListFormat.supportedLocalesOf([
      "en-US",
      "en-GB"
    ], {
      localeMatcher: "lookup"
    });

var formatter = new Intl.ListFormat(undefined, {
      type: "conjunction",
      style: "long"
    });

console.log(formatter.resolvedOptions());

console.log(formatter.format([
          "one",
          "two",
          "three"
        ]));

console.log(formatter.formatToParts([
          "one",
          "two",
          "three"
        ]));

export {
  _formatter ,
  formatter ,
}
/*  Not a pure module */
