// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_exn from "rescript/lib/es6/js_exn.js";
import * as Intl__LocaleTest from "./Intl__LocaleTest.mjs";
import * as Caml_js_exceptions from "rescript/lib/es6/caml_js_exceptions.js";
import * as Intl__CollatorTest from "./Intl__CollatorTest.mjs";
import * as Intl__SegmenterTest from "./Intl__SegmenterTest.mjs";
import * as Intl__ListFormatTest from "./Intl__ListFormatTest.mjs";
import * as Intl__PluralRulesTest from "./Intl__PluralRulesTest.mjs";
import * as Intl__NumberFormatTest from "./Intl__NumberFormatTest.mjs";
import * as Intl__DateTimeFormatTest from "./Intl__DateTimeFormatTest.mjs";
import * as Intl__RelativeTimeFormatTest from "./Intl__RelativeTimeFormatTest.mjs";

console.log("---");

console.log("Intl");

console.log(Intl.getCanonicalLocales("EN-US"));

console.log(Intl.getCanonicalLocales([
          "EN-US",
          "Fr"
        ]));

try {
  console.log(Intl.getCanonicalLocales("bloop"));
}
catch (raw_e){
  var e = Caml_js_exceptions.internalToOCamlException(raw_e);
  if (e.RE_EXN_ID === Js_exn.$$Error) {
    console.error(e._1);
  } else {
    throw e;
  }
}

try {
  console.log(Intl.supportedValuesOf("calendar"));
  console.log(Intl.supportedValuesOf("collation"));
  console.log(Intl.supportedValuesOf("currency"));
  console.log(Intl.supportedValuesOf("numberingSystem"));
  console.log(Intl.supportedValuesOf("timeZone"));
  console.log(Intl.supportedValuesOf("unit"));
}
catch (raw_e$1){
  var e$1 = Caml_js_exceptions.internalToOCamlException(raw_e$1);
  if (e$1.RE_EXN_ID === Js_exn.$$Error) {
    console.error(e$1._1);
  } else {
    throw e$1;
  }
}

try {
  Intl.supportedValuesOf("someInvalidKey");
  console.error("Shouldn't have been hit");
}
catch (raw_e$2){
  var e$2 = Caml_js_exceptions.internalToOCamlException(raw_e$2);
  if (e$2.RE_EXN_ID === Js_exn.$$Error) {
    console.error(e$2._1);
  } else {
    throw e$2;
  }
}

var collator = Intl__CollatorTest.collator;

var resolvedOptions = Intl__DateTimeFormatTest.resolvedOptions;

var timeZone = Intl__DateTimeFormatTest.timeZone;

var locale = Intl__LocaleTest.locale;

var currencyFormatter = Intl__NumberFormatTest.currencyFormatter;

var roundingFormatter = Intl__NumberFormatTest.roundingFormatter;

var groupingFormatter1 = Intl__NumberFormatTest.groupingFormatter1;

var groupingFormatter2 = Intl__NumberFormatTest.groupingFormatter2;

var sigFormatter = Intl__NumberFormatTest.sigFormatter;

var options = Intl__NumberFormatTest.options;

var formatter = Intl__SegmenterTest.formatter;

var segments = Intl__SegmenterTest.segments;

export {
  collator ,
  resolvedOptions ,
  timeZone ,
  locale ,
  currencyFormatter ,
  roundingFormatter ,
  groupingFormatter1 ,
  groupingFormatter2 ,
  sigFormatter ,
  options ,
  formatter ,
  segments ,
}
/*  Not a pure module */
