// Generated by ReScript, PLEASE EDIT WITH CARE


console.log("---");

console.log("Intl.Collator");

new Intl.Collator(undefined, undefined);

new Intl.Collator(["en-US"], undefined);

var _collator = new Intl.Collator([
      "en-US",
      "en-GB"
    ], undefined);

var collator = new Intl.Collator(["en-US"], {
      sensitivity: "base",
      ignorePunctuation: true,
      numeric: true,
      caseFirst: "upper"
    });

Intl.Collator.supportedLocalesOf([
      "en-US",
      "en-GB"
    ]);

Intl.Collator.supportedLocalesOf([
      "en-US",
      "en-GB"
    ], {
      localeMatcher: "lookup"
    });

console.log(collator.resolvedOptions());

console.log(collator.compare("hi", "hï"));

console.log(Intl.Collator.supportedLocalesOf(["hi"]));

export {
  _collator ,
  collator ,
}
/*  Not a pure module */
