// Generated by ReScript, PLEASE EDIT WITH CARE


console.log("---");

console.log("Intl.Segmenter");

Intl.Segmenter.supportedLocalesOf([
      "en-US",
      "en-GB"
    ]);

Intl.Segmenter.supportedLocalesOf([
      "en-US",
      "en-GB"
    ], {
      localeMatcher: "lookup"
    });

new Intl.Segmenter();

new Intl.Segmenter("en-US");

new Intl.Segmenter([
      "en-US",
      "en-GB"
    ]);

new Intl.Segmenter(undefined, {
      granularity: "word"
    });

new Intl.Segmenter("en-US", {
      granularity: "word"
    });

var formatter = new Intl.Segmenter(["en-US"], {
      granularity: "word"
    });

console.log(formatter.resolvedOptions());

var segments = formatter.segment("This is a sentence with several words");

console.log(segments);

console.log(segments.containing());

console.log(segments.containing(1));

export {
  formatter ,
  segments ,
}
/*  Not a pure module */
