// Generated by ReScript, PLEASE EDIT WITH CARE


function equal(a, b) {
  return a === b;
}

function compare(a, b) {
  return a - b | 0;
}

function fromString(radix, x) {
  var maybeInt = radix !== undefined ? parseInt(x, radix) : parseInt(x);
  if (isNaN(maybeInt) || maybeInt > 2147483647 || maybeInt < -2147483648) {
    return ;
  } else {
    return maybeInt | 0;
  }
}

var Constants = {
  minValue: -2147483648,
  maxValue: 2147483647
};

export {
  Constants ,
  equal ,
  compare ,
  fromString ,
}
/* No side effect */
