// Generated by ReScript, PLEASE EDIT WITH CARE


var $$EvalError = {};

var $$RangeError = {};

var $$ReferenceError = {};

var $$SyntaxError = {};

var $$TypeError = {};

var $$URIError = {};

export {
  $$EvalError ,
  $$RangeError ,
  $$ReferenceError ,
  $$SyntaxError ,
  $$TypeError ,
  $$URIError ,
}
/* No side effect */
