// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_splice_call from "rescript/lib/es6/caml_splice_call.js";

var Constants = {};

function minMany(arr) {
  if (arr.length !== 0) {
    return Caml_splice_call.spliceApply(Math.min, [arr]);
  } else {
    return 0;
  }
}

function maxMany(arr) {
  if (arr.length !== 0) {
    return Caml_splice_call.spliceApply(Math.max, [arr]);
  } else {
    return 0;
  }
}

var Int = {
  minMany: minMany,
  maxMany: maxMany
};

function minMany$1(arr) {
  if (arr.length !== 0) {
    return Caml_splice_call.spliceApply(Math.min, [arr]);
  } else {
    return 0.0;
  }
}

function maxMany$1(arr) {
  if (arr.length !== 0) {
    return Caml_splice_call.spliceApply(Math.max, [arr]);
  } else {
    return 0.0;
  }
}

export {
  Constants ,
  Int ,
  minMany$1 as minMany,
  maxMany$1 as maxMany,
}
/* No side effect */
