// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml from "rescript/lib/es6/caml.js";

var UTC = {};

function equal(a, b) {
  return a.getTime() === b.getTime();
}

function compare(a, b) {
  return Caml.float_compare(a.getTime(), b.getTime());
}

export {
  UTC ,
  equal ,
  compare ,
}
/* No side effect */
