// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Core__Ordering from "./Core__Ordering.mjs";

var Constants = {};

function equal(a, b) {
  return a === b;
}

function compare(a, b) {
  if (a < b) {
    return Core__Ordering.less;
  } else if (a > b) {
    return Core__Ordering.greater;
  } else {
    return Core__Ordering.equal;
  }
}

function fromString(i) {
  var i$1 = parseFloat(i);
  if (isNaN(i$1)) {
    return ;
  } else {
    return i$1;
  }
}

export {
  Constants ,
  equal ,
  compare ,
  fromString ,
}
/* No side effect */
