// Generated by ReScript, PLEASE EDIT WITH CARE


function isLess(ord) {
  return ord < 0;
}

function isEqual(ord) {
  return ord === 0;
}

function isGreater(ord) {
  return ord > 0;
}

function invert(ord) {
  return - ord;
}

function fromInt(n) {
  if (n < 0) {
    return -1;
  } else if (n > 0) {
    return 1;
  } else {
    return 0;
  }
}

var less = -1;

var equal = 0;

var greater = 1;

export {
  less ,
  equal ,
  greater ,
  isLess ,
  isEqual ,
  isGreater ,
  invert ,
  fromInt ,
}
/* No side effect */
