// Generated by ReScript, PLEASE EDIT WITH CARE


function classify(value) {
  var match = Object.prototype.toString.call(value);
  switch (match) {
    case "[object Array]" :
        return {
                TAG: /* Array */4,
                _0: value
              };
    case "[object Boolean]" :
        return {
                TAG: /* Bool */0,
                _0: value
              };
    case "[object Null]" :
        return /* Null */0;
    case "[object Number]" :
        return {
                TAG: /* Number */2,
                _0: value
              };
    case "[object String]" :
        return {
                TAG: /* String */1,
                _0: value
              };
    default:
      return {
              TAG: /* Object */3,
              _0: value
            };
  }
}

var Decode = {
  classify: classify
};

var Encode = {};

export {
  Decode ,
  Encode ,
}
/* No side effect */
