// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_option from "rescript/lib/es6/caml_option.js";

function value(v) {
  return {
          done: false,
          value: Caml_option.some(v)
        };
}

function done(finalValue) {
  return {
          done: true,
          value: finalValue
        };
}

async function forEach(iterator, f) {
  var iteratorDone = false;
  while(!iteratorDone) {
    var match = await iterator.next();
    f(match.value);
    iteratorDone = match.done;
  };
}

var make = (function makeAsyncIterator(next) {
  return {
    next,
    [Symbol.asyncIterator]() {
      return this;
    }
  }
});

export {
  make ,
  value ,
  done ,
  forEach ,
}
/* No side effect */
