// Generated by ReScript, PLEASE EDIT WITH CARE


var Common;

var Collator;

var DateTimeFormat;

var ListFormat;

var Locale;

var NumberFormat;

var PluralRules;

var RelativeTimeFormat;

var Segmenter;

var Segments;

export {
  Common ,
  Collator ,
  DateTimeFormat ,
  ListFormat ,
  Locale ,
  NumberFormat ,
  PluralRules ,
  RelativeTimeFormat ,
  Segmenter ,
  Segments ,
}
/* No side effect */
