// Generated by ReScript, PLEASE EDIT WITH CARE


function fromString(radix, x) {
  var maybeInt = radix !== undefined ? parseInt(x, radix) : parseInt(x);
  if (isNaN(maybeInt) || maybeInt > 2147483647 || maybeInt < -2147483648) {
    return ;
  } else {
    return maybeInt;
  }
}

var Constants = {
  minValue: -2147483648,
  maxValue: 2147483647
};

export {
  Constants ,
  fromString ,
}
/* No side effect */
