// Generated by ReScript, PLEASE EDIT WITH CARE


function indexOfOpt(s, search) {
  var index = s.indexOf(search);
  if (index !== -1) {
    return index;
  }
  
}

function lastIndexOfOpt(s, search) {
  var index = s.lastIndexOf(search);
  if (index !== -1) {
    return index;
  }
  
}

function searchOpt(s, re) {
  var index = s.search(re);
  if (index !== -1) {
    return index;
  }
  
}

export {
  indexOfOpt ,
  lastIndexOfOpt ,
  searchOpt ,
}
/* No side effect */
