// Generated by ReScript, PLEASE EDIT WITH CARE


function fromStringExn(param) {
  switch (param) {
    case "false" :
        return false;
    case "true" :
        return true;
    default:
      throw {
            RE_EXN_ID: "Invalid_argument",
            _1: "Bool.fromStringExn: value is neither \"true\" nor \"false\"",
            Error: new Error()
          };
  }
}

function fromString(param) {
  switch (param) {
    case "false" :
        return false;
    case "true" :
        return true;
    default:
      return ;
  }
}

function xor(a, b) {
  return a !== b;
}

function xnor(a, b) {
  return a === b;
}

function nand(a, b) {
  return !(a && b);
}

function nor(a, b) {
  return !(a || b);
}

export {
  fromStringExn ,
  fromString ,
  xnor ,
  xor ,
  nand ,
  nor ,
}
/* No side effect */
