// Generated by ReScript, PLEASE EDIT WITH CARE


function equal(a, b) {
  return a === b;
}

function compare(a, b) {
  if (a === b) {
    return 0;
  } else if (a > b) {
    return 1;
  } else {
    return -1;
  }
}

function indexOfOpt(s, search) {
  var index = s.indexOf(search);
  if (index !== -1) {
    return index;
  }
  
}

function lastIndexOfOpt(s, search) {
  var index = s.lastIndexOf(search);
  if (index !== -1) {
    return index;
  }
  
}

function searchOpt(s, re) {
  var index = s.search(re);
  if (index !== -1) {
    return index;
  }
  
}

export {
  equal ,
  compare ,
  indexOfOpt ,
  lastIndexOfOpt ,
  searchOpt ,
}
/* No side effect */
