// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_option from "rescript/lib/es6/caml_option.js";

function fromOption(option) {
  if (option !== undefined) {
    return Caml_option.valFromOption(option);
  }
  
}

export {
  fromOption ,
}
/* No side effect */
