// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_obj from "rescript/lib/es6/caml_obj.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";

var Constants = {};

function equal(a, b) {
  return a === b;
}

function compare(a, b) {
  if (a < b) {
    return -1;
  } else if (a > b) {
    return 1;
  } else {
    return 0;
  }
}

function fromString(i) {
  var i$1 = parseFloat(i);
  if (isNaN(i$1)) {
    return ;
  } else {
    return i$1;
  }
}

function clamp(min, max, value) {
  var value$1;
  if (max !== undefined) {
    var max$1 = Caml_option.valFromOption(max);
    value$1 = Caml_obj.lessthan(max$1, value) ? max$1 : value;
  } else {
    value$1 = value;
  }
  if (min === undefined) {
    return value$1;
  }
  var min$1 = Caml_option.valFromOption(min);
  if (Caml_obj.greaterthan(min$1, value$1)) {
    return min$1;
  } else {
    return value$1;
  }
}

export {
  Constants ,
  equal ,
  compare ,
  fromString ,
  clamp ,
}
/* No side effect */
