// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Core__Error from "./Core__Error.mjs";

var $$Array;

var Console;

var $$DataView;

var $$Date;

var Dict;

var $$Error;

var Float;

var Int;

var $$BigInt;

var $$Math;

var Null;

var Nullable;

var $$Object;

var Ordering;

var $$Promise;

var $$RegExp;

var $$String;

var Char;

var $$Symbol;

var Type;

var $$JSON;

var Iterator;

var AsyncIterator;

var $$Map;

var $$WeakMap;

var $$Set;

var $$WeakSet;

var $$ArrayBuffer;

var TypedArray;

var $$Float32Array;

var $$Float64Array;

var $$Int8Array;

var $$Int16Array;

var $$Int32Array;

var $$Uint8Array;

var $$Uint16Array;

var $$Uint32Array;

var $$Uint8ClampedArray;

var $$BigInt64Array;

var $$BigUint64Array;

var $$Intl;

var Exn;

var $$Option;

var List;

var Result;

var panic = Core__Error.panic;

export {
  $$Array ,
  Console ,
  $$DataView ,
  $$Date ,
  Dict ,
  $$Error ,
  Float ,
  Int ,
  $$BigInt ,
  $$Math ,
  Null ,
  Nullable ,
  $$Object ,
  Ordering ,
  $$Promise ,
  $$RegExp ,
  $$String ,
  Char ,
  $$Symbol ,
  Type ,
  $$JSON ,
  Iterator ,
  AsyncIterator ,
  $$Map ,
  $$WeakMap ,
  $$Set ,
  $$WeakSet ,
  $$ArrayBuffer ,
  TypedArray ,
  $$Float32Array ,
  $$Float64Array ,
  $$Int8Array ,
  $$Int16Array ,
  $$Int32Array ,
  $$Uint8Array ,
  $$Uint16Array ,
  $$Uint32Array ,
  $$Uint8ClampedArray ,
  $$BigInt64Array ,
  $$BigUint64Array ,
  $$Intl ,
  Exn ,
  $$Option ,
  List ,
  Result ,
  panic ,
}
/* No side effect */
